# Use official PostgreSQL image as the base image
FROM postgres:latest

# Expose port 5432 to the outside world
EXPOSE 5432

# Environment variables
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
